FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive

ENV LANG C.UTF-8

ENV GOROOT /usr/local/go

ENV GOPATH /usr/local

ENV PATH $GOPATH/bin:$GOROOT/bin:$PATH

WORKDIR /mint

COPY . /mint

RUN apt-get update && apt-get install -yq git jq && \
    /mint/build/install.sh

CMD ["/mint/run.sh", "/mint/tests.sh"]
