FROM ubuntu:16.04

ENV GOROOT /usr/local/go

ENV GOPATH /usr/local

ENV PATH $GOPATH/bin:$GOROOT/bin:$PATH

WORKDIR /mint

COPY . /mint

RUN apt-get update && apt-get install -yq \
    git && /mint/buildscripts/mint-deps.sh && \
    /mint/buildscripts/initData.sh
  
CMD /mint/run.sh